### ISSUE TITLE
前端加密的密文是不是不可以到后端解密？

### ISSUE THREAD

**Issue by geyiwei-hub** [luanxuechao/hutool-js-sm2-demo#1]

**Comment by luanxuechao** [comment]
可以啊，提供你的示例代码？

**Comment by ghost** [comment]
直接pull下来的代码，不修改公私钥，在前端使用公钥加密，后端解不了。
我已经重新封装了一个java库，保证前后端 公私钥、加解密 的强一致性。
github：https://github.com/antherd/sm-crypto/
